# groups are a set of related rules
groups:
  - name: node_load
    rules:
      - record: node:cpu_load:avg
        expr: 1 - avg(irate(node_cpu_seconds_total{mode="idle",instance="node-exporter:9100"}[5m]))
      - alert: high_cpu_load
        expr: node:cpu_load:avg > .9
        for: 5m
        annotations:
          overview: 'CPU load is {{  printf "%.2f" $value }}%'